### ISSUE TITLE
Typo in Algorithm 2 in the blog post?

### ISSUE THREAD

**Issue by vadimkantorov** [aangelopoulos/conformal_classification#6]
At http://people.eecs.berkeley.edu/~angelopoulos/blog/posts/conformal-classification/ it computes `\lambda 1{j > k_{reg}}`. Should `j` be `i` instead? If not, why does it make sense to compare an image index to the size of prediction set? (`j` appears referred to as image index) Thanks!

**Comment by aangelopoulos** [comment]
Yep, you're right! Thanks for the fix :)
